# Generated by Django 2.2.2 on 2019-07-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email address')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_client', models.BooleanField(default=False)),
                ('is_tutor', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100, verbose_name='Full name')),
                ('bio', models.CharField(max_length=1000, verbose_name='Bio')),
                ('location', models.CharField(max_length=1000, verbose_name='Location')),
                ('gender', models.CharField(max_length=20, verbose_name='Gender')),
                ('title', models.CharField(max_length=1000, verbose_name='Overview title')),
                ('overview', models.TextField(verbose_name='Overview')),
                ('expertise', models.CharField(max_length=1000, verbose_name='Overview')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
