# Generated by Django 2.2.2 on 2019-07-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Verified'),
        ),
    ]
