# Generated by Django 2.2.2 on 2019-07-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_verification_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_img',
            field=models.TextField(blank=True, verbose_name='Profile Image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='expertise',
            field=models.CharField(max_length=1000, verbose_name='Expertise'),
        ),
    ]
