# Generated by Django 2.2.2 on 2019-07-06 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tuition', '0009_answer_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(verbose_name='Rating')),
                ('feedback', models.TextField(verbose_name='Feedback')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuition.Ad')),
            ],
        ),
    ]
