# Generated by Django 2.2.2 on 2019-07-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='days',
            field=models.IntegerField(verbose_name='How many days a week'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='salary',
            field=models.IntegerField(verbose_name='Monthly Salary'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='std_count',
            field=models.IntegerField(verbose_name='Student Count'),
        ),
    ]
