# Generated by Django 2.2.2 on 2019-07-05 11:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0004_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='taken',
            field=models.BooleanField(default=False, verbose_name='Taken'),
        ),
        migrations.AddField(
            model_name='ad',
            name='timeout',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Run This Ad Until'),
            preserve_default=False,
        ),
    ]
