# Generated by Django 2.2.2 on 2019-07-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0005_auto_20190705_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='ad_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Ad time'),
        ),
    ]
