# Generated by Django 2.2.2 on 2019-07-05 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tuition', '0007_answer_assignee_proposal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='tutor',
        ),
        migrations.AddField(
            model_name='answer',
            name='proposal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tuition.Proposal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='tutor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
