# Generated by Django 2.2.2 on 2019-07-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0009_answer_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignee',
            name='to_date',
            field=models.DateField(null=True, verbose_name='Date finished'),
        ),
    ]
